# ML-Scheduler Data Collection Configuration
# MLOps Lifecycle - Etape 3 Configuration

prometheus:
  url: "http://10.110.190.83:9090"
  timeout: 30
  retry_attempts: 3

collection:
  # Periode de collecte (jours)
  default_period_days: 30
  minimum_required_days: 7
  
  # Resolution temporelle
  step_interval: "1m"  # 1 minute resolution
  
  # Metriques critiques nodes
  node_metrics:
    - name: "node_cpu_seconds_total"
      type: "rate"
      critical: true
      description: "CPU usage par mode et node"
    - name: "node_memory_MemAvailable_bytes" 
      type: "instant"
      critical: true
      description: "Memoire disponible par node"
    - name: "node_memory_MemTotal_bytes"
      type: "instant" 
      critical: true
      description: "Memoire totale par node"
    - name: "node_load1"
      type: "instant"
      critical: true
      description: "Load average 1 minute"
    - name: "node_load5"
      type: "instant"
      critical: true  
      description: "Load average 5 minutes"
    - name: "node_filesystem_avail_bytes"
      type: "instant"
      critical: false
      description: "Espace disque disponible"
    - name: "node_network_receive_bytes_total"
      type: "rate"
      critical: false
      description: "Bytes reseau recus"
    - name: "node_network_transmit_bytes_total"
      type: "rate" 
      critical: false
      description: "Bytes reseau transmis"
  
  # Metriques critiques pods/containers
  container_metrics:
    - name: "container_cpu_usage_seconds_total"
      type: "rate"
      critical: true
      description: "CPU usage par container"
    - name: "container_memory_usage_bytes"
      type: "instant"
      critical: true
      description: "Memory usage par container"
    - name: "container_memory_rss"
      type: "instant"
      critical: true
      description: "RSS memory par container"
    - name: "kube_pod_info"
      type: "instant"
      critical: true
      description: "Metadata pods"
    - name: "kube_pod_status_phase" 
      type: "instant"
      critical: true
      description: "Status phase pods"
    - name: "kube_pod_container_status_restarts_total"
      type: "instant"
      critical: true
      description: "Restarts containers"

storage:
  # Chemins stockage donnees
  base_path: "./data/historical"
  nodes_path: "./data/historical/nodes"
  pods_path: "./data/historical/pods"
  events_path: "./data/historical/events"
  
  # Format fichiers
  output_format: "parquet"  # Plus efficace que CSV
  compression: "snappy"
  
quality:
  # Seuils qualite donnees
  minimum_coverage_percentage: 80
  minimum_quality_score: 75
  maximum_missing_data_percentage: 25
  
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"