apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ml-experiments
  namespace: wassimmezrani
  labels:
    app: ml-scheduler
    component: experiments
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 15Gi
