apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ml-models-storage
  namespace: wassimmezrani
  labels:
    app: ml-scheduler
    component: models-storage
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
