---
# Common tasks for all nodes
- name: Update system packages
  apt:
    update_cache: true
    upgrade: dist

- name: Install common packages
  apt:
    name:
      - curl
      - wget
      - vim
      - htop
      - net-tools
      - git
    state: present

- name: Disable swap
  command: swapoff -a
  when: ansible_swaptotal_mb > 0

- name: Remove swap from fstab
  lineinfile:
    path: /etc/fstab
    regexp: '^.*swap.*$'
    state: absent

- name: Configure sysctl for Kubernetes
  sysctl:
    name: "{{ item }}"
    value: '1'
    state: present
    reload: true
  loop:
    - net.bridge.bridge-nf-call-iptables
    - net.bridge.bridge-nf-call-ip6tables
    - net.ipv4.ip_forward
