---
k8s_version: "1.31.4"
flannel_url: "https://github.com/flannel-io/flannel/releases/latest/download/kube-flannel.yml"
ingress_url: "https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v1.8.1/deploy/static/provider/baremetal/deploy.yaml"