---
# Handlers for common role

- name: restart ntp
  systemd:
    name: ntp
    state: restarted

- name: reload sysctl
  command: sysctl --system

- name: reboot system
  reboot:
    reboot_timeout: 300