---
# HAProxy role tasks
- name: Install HAProxy
  apt:
    name: haproxy
    state: present
    update_cache: true

- name: Configure HAProxy
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
    backup: true
  notify: restart haproxy

- name: Start and enable HAProxy
  systemd:
    name: haproxy
    state: started
    enabled: true
