---
# HAProxy specific variables (based on actual configuration)
haproxy_stats_port: 8404
haproxy_api_port: 6443
haproxy_http_port: 80
haproxy_https_port: 443

# Stats authentication
haproxy_stats_user: admin
haproxy_stats_password: admin123

# Load balancer backend configuration
haproxy_backends:
  kubernetes_apiserver:
    port: 6443
    mode: tcp
    balance: roundrobin
    check_params: "check fall 3 rise 2"
  kubernetes_ingress_http:
    port: "{{ ingress_http_nodeport }}"
    mode: tcp
    balance: roundrobin
    check_params: "check fall 3 rise 2"
  kubernetes_ingress_https:
    port: "{{ ingress_https_nodeport }}"
    mode: tcp
    balance: roundrobin
    check_params: "check fall 3 rise 2"

# HAProxy logging configuration
haproxy_log_server: "127.0.0.1:514"
haproxy_log_facility: "local0"

# HAProxy timeouts (actual configuration)
haproxy_timeout_connect: "10s"
haproxy_timeout_client: "1m"
haproxy_timeout_server: "1m"
haproxy_timeout_check: "10s"

# HAProxy global configuration
haproxy_chroot_dir: "/var/lib/haproxy"
haproxy_socket_path: "/run/haproxy/admin.sock"
haproxy_socket_mode: "660"
haproxy_socket_level: "admin"
haproxy_user: "haproxy"
haproxy_group: "haproxy"
haproxy_daemon: true

# Default configuration
haproxy_mode: "http"
haproxy_option_httplog: true
haproxy_option_dontlognull: true
haproxy_option_log_health_checks: true
haproxy_option_forwardfor: true
haproxy_option_http_server_close: true

# Frontend configurations
haproxy_frontends:
  kubernetes_apiserver:
    name: "kubernetes-apiserver-frontend"
    bind: "*:6443"
    mode: "tcp"
    option: "tcplog"
    default_backend: "kubernetes-apiserver-backend"
  
  kubernetes_ingress_http:
    name: "kubernetes-ingress-http-frontend"
    bind: "*:80"
    mode: "tcp"
    option: "tcplog"
    default_backend: "kubernetes-ingress-http-backend"
  
  kubernetes_ingress_https:
    name: "kubernetes-ingress-https-frontend"
    bind: "*:443"
    mode: "tcp"
    option: "tcplog"
    default_backend: "kubernetes-ingress-https-backend"

# Stats configuration
haproxy_stats_socket_enabled: true
haproxy_stats_refresh: "30s"
haproxy_stats_admin_if: "TRUE"
