---
k8s_cluster_name: "mlops-cluster"
k8s_version: "1.31.4"
k8s_control_plane_endpoint: "10.110.190.21:6443"
container_runtime: containerd
cni_plugin: flannel
ingress_controller: nginx
ingress_http_nodeport: 32624
ingress_https_nodeport: 31316

k8s_packages:
  - kubelet=1.31.4-1.1
  - kubeadm=1.31.4-1.1
  - kubectl=1.31.4-1.1

pod_network_cidr: "10.244.0.0/16"
service_cidr: "10.96.0.0/12"
