---
# Handlers for kubernetes-worker role

- name: restart containerd
  systemd:
    name: containerd
    state: restarted

- name: restart kubelet
  systemd:
    name: kubelet
    state: restarted

- name: reload kubelet
  systemd:
    name: kubelet
    state: reloaded