---
# Cluster Documentation and Status Check Playbook
- name: Document Current MLOps Infrastructure
  hosts: all
  gather_facts: true
  tasks:
    - name: Create documentation directory
      file:
        path: /tmp/mlops-cluster-docs
        state: directory
      delegate_to: localhost
      run_once: true

    - name: Document system information
      copy:
        content: |
          # MLOps Infrastructure Documentation
          Generated on: {{ ansible_date_time.iso8601 }}
          
          ## Host: {{ inventory_hostname }}
          - IP Address: {{ ansible_host }}
          - OS: {{ ansible_distribution }} {{ ansible_distribution_version }}
          - Kernel: {{ ansible_kernel }}
          - Architecture: {{ ansible_architecture }}
          - Memory: {{ ansible_memtotal_mb }}MB
          - CPU Cores: {{ ansible_processor_vcpus }}
          - Disk Usage: {{ ansible_mounts[0].size_total | int // 1024 // 1024 // 1024 }}GB Total
        dest: /tmp/mlops-cluster-docs/{{ inventory_hostname }}-info.md
      delegate_to: localhost

- name: Document Kubernetes Cluster Status
  hosts: k8s-masters[0]
  tasks:
    - name: Get cluster nodes
      command: kubectl get nodes -o yaml
      register: cluster_nodes
      
    - name: Get cluster services
      command: kubectl get svc --all-namespaces -o yaml
      register: cluster_services
      
    - name: Get ingress controller info
      command: kubectl get svc -n ingress-nginx -o yaml
      register: ingress_info
      
    - name: Save cluster documentation
      copy:
        content: |
          # Kubernetes Cluster Status
          Generated on: {{ ansible_date_time.iso8601 }}
          
          ## Cluster Nodes
          {{ cluster_nodes.stdout }}
          
          ## All Services
          {{ cluster_services.stdout }}
          
          ## Ingress Controller
          {{ ingress_info.stdout }}
        dest: /tmp/mlops-cluster-docs/kubernetes-cluster-status.yaml
      delegate_to: localhost

- name: Document HAProxy Configuration
  hosts: haproxy
  tasks:
    - name: Get HAProxy configuration
      slurp:
        src: /etc/haproxy/haproxy.cfg
      register: haproxy_config
      
    - name: Get HAProxy status
      command: systemctl status haproxy
      register: haproxy_status
      
    - name: Save HAProxy documentation
      copy:
        content: |
          # HAProxy Load Balancer Configuration
          Generated on: {{ ansible_date_time.iso8601 }}
          
          ## Configuration File
          ```
          {{ haproxy_config.content | b64decode }}
          ```
          
          ## Service Status
          ```
          {{ haproxy_status.stdout }}
          ```
        dest: /tmp/mlops-cluster-docs/haproxy-config.md
      delegate_to: localhost
