---
# Playbook to generate new join tokens for Kubernetes cluster
- name: Generate New Kubernetes Join Tokens
  hosts: k8s-masters[0]
  become: true
  gather_facts: true
  vars:
    control_plane_endpoint: "{{ k8s_control_plane_endpoint | default('10.110.190.21:6443') }}"
  tasks:
    - name: Generate new join token
      command: kubeadm token create --print-join-command
      register: new_join_command
      
    - name: Generate new certificate key for control plane
      command: kubeadm init phase upload-certs --upload-certs
      register: new_certificate_key_output
      
    - name: Extract new certificate key
      set_fact:
        new_certificate_key: "{{ new_certificate_key_output.stdout_lines[-1] }}"
      when: 
        - new_certificate_key_output.stdout_lines is defined
        - new_certificate_key_output.stdout_lines | length > 0
      
    - name: Extract new join command components
      set_fact:
        new_kubeadm_token: "{{ new_join_command.stdout.split('--token ')[1].split(' ')[0] }}"
        new_ca_cert_hash: "{{ new_join_command.stdout.split('--discovery-token-ca-cert-hash ')[1].split(' ')[0] }}"
      when: new_join_command.stdout is defined
      
    - name: Display new join information
      debug:
        msg: |
          ================================
          NEW KUBERNETES JOIN INFORMATION
          ================================
          
          Control Plane Endpoint: {{ control_plane_endpoint }}
          Token: {{ new_kubeadm_token | default('FAILED_TO_GENERATE') }}
          CA Cert Hash: {{ new_ca_cert_hash | default('FAILED_TO_GENERATE') }}
          Certificate Key: {{ new_certificate_key | default('FAILED_TO_GENERATE') }}
          
          Worker Join Command:
          kubeadm join {{ control_plane_endpoint }} --token {{ new_kubeadm_token | default('TOKEN') }} --discovery-token-ca-cert-hash {{ new_ca_cert_hash | default('HASH') }}
          
          Master Join Command:
          kubeadm join {{ control_plane_endpoint }} --token {{ new_kubeadm_token | default('TOKEN') }} --discovery-token-ca-cert-hash {{ new_ca_cert_hash | default('HASH') }} --control-plane --certificate-key {{ new_certificate_key | default('CERT_KEY') }}
          
          ================================
          
    - name: Save new join information to file
      copy:
        content: |
          # Kubernetes Cluster Join Information
          # Generated on: {{ ansible_date_time.date }} {{ ansible_date_time.time }}
          
          # Control Plane Endpoint
          CONTROL_PLANE_ENDPOINT={{ control_plane_endpoint }}
          
          # Join Token
          KUBEADM_TOKEN={{ new_kubeadm_token | default('FAILED_TO_GENERATE') }}
          
          # CA Certificate Hash
          CA_CERT_HASH={{ new_ca_cert_hash | default('FAILED_TO_GENERATE') }}
          
          # Certificate Key (for control plane nodes)
          CERTIFICATE_KEY={{ new_certificate_key | default('FAILED_TO_GENERATE') }}
          
          # Worker Join Command:
          kubeadm join {{ control_plane_endpoint }} --token {{ new_kubeadm_token | default('TOKEN') }} --discovery-token-ca-cert-hash {{ new_ca_cert_hash | default('HASH') }}
          
          # Master Join Command:
          kubeadm join {{ control_plane_endpoint }} --token {{ new_kubeadm_token | default('TOKEN') }} --discovery-token-ca-cert-hash {{ new_ca_cert_hash | default('HASH') }} --control-plane --certificate-key {{ new_certificate_key | default('CERT_KEY') }}
        dest: "/home/{{ ansible_user }}/kubeadm-join-tokens-{{ ansible_date_time.epoch }}.txt"
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: '0600'
