---
# HAProxy configuration playbook
- name: Setup HAProxy for Kubernetes API Load Balancing
  hosts: haproxy
  become: true
  tasks:
    - name: Install HAProxy
      apt:
        name: haproxy
        state: present
        update_cache: yes

    - name: Configure HAProxy for Kubernetes API
      template:
        src: haproxy.cfg.j2
        dest: /etc/haproxy/haproxy.cfg
        backup: yes
      notify: restart haproxy

    - name: Start and enable HAProxy service
      systemd:
        name: haproxy
        state: started
        enabled: yes

  handlers:
    - name: restart haproxy
      systemd:
        name: haproxy
        state: restarted
