---
- name: Configure MetalLB IP Pool
  hosts: k8s-masters[0]
  become: true
  tasks:
    - name: Create MetalLB configuration
      copy:
        content: |
          apiVersion: metallb.io/v1beta1
          kind: IPAddressPool
          metadata:
            name: default-pool
            namespace: metallb-system
          spec:
            addresses:
            - {{ metallb_ip_pool_range }}
          ---
          apiVersion: metallb.io/v1beta1
          kind: L2Advertisement
          metadata:
            name: default-l2-adv
            namespace: metallb-system
          spec:
            ipAddressPools:
            - default-pool
        dest: /tmp/metallb-pool-config.yaml
      when: metallb_ip_pool_range is defined
    
    - name: Apply configuration
      become_user: "{{ ansible_user }}"
      shell: kubectl apply -f /tmp/metallb-pool-config.yaml
      when: metallb_ip_pool_range is defined
    
    - name: Verify configuration
      become_user: "{{ ansible_user }}"
      shell: kubectl get ipaddresspool,l2advertisement -n metallb-system
      register: status
    
    - name: Show status
      debug:
        var: status.stdout_lines