apiVersion: kubeflow.org/v1
kind: Notebook
metadata:
  name: ml-scheduler-dev
  namespace: wassimmezrani
  labels:
    app: ml-scheduler
    component: jupyter-development
  annotations:
    description: "Advanced ML development environment for ML-Scheduler"
    notebooks.kubeflow.org/server-type: jupyter
spec:
  template:
    spec:
      serviceAccountName: default-editor
      containers:
      - name: ml-scheduler
        image: charmedkubeflow/jupyter-scipy:1.10.0-0be57a5
        env:
        - name: JUPYTER_ENABLE_LAB
          value: "yes"
        - name: PROMETHEUS_URL
          value: "http://prometheus-k8s.monitoring.svc.cluster.local:9090"
        - name: FEAST_REGISTRY_PATH
          value: "/home/jovyan/ml-feature-store/registry"
        - name: MLFLOW_TRACKING_URI
          value: "http://mlflow-server.kubeflow.svc.cluster.local:5000"
        ports:
        - containerPort: 8888
          name: notebook-port
          protocol: TCP
        resources:
          requests:
            cpu: "2"
            memory: "8Gi"
          limits:
            cpu: "4"
            memory: "16Gi"
        volumeMounts:
        - name: workspace
          mountPath: /home/jovyan
        - name: historical-data
          mountPath: /home/jovyan/ml-historical-data
        - name: models-storage
          mountPath: /home/jovyan/ml-models-storage
        - name: experiments
          mountPath: /home/jovyan/ml-experiments
        - name: feature-store
          mountPath: /home/jovyan/ml-feature-store
        - name: dshm
          mountPath: /dev/shm
        workingDir: /home/jovyan
      volumes:
      - name: workspace
        persistentVolumeClaim:
          claimName: ml-scheduler-workspace
      - name: historical-data
        persistentVolumeClaim:
          claimName: ml-historical-data
      - name: models-storage
        persistentVolumeClaim:
          claimName: ml-models-storage
      - name: experiments
        persistentVolumeClaim:
          claimName: ml-experiments
      - name: feature-store
        persistentVolumeClaim:
          claimName: ml-feature-store
      - name: dshm
        emptyDir:
          medium: Memory
          sizeLimit: 4Gi
