apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ml-scheduler-pipeline-runner
rules:
- apiGroups:
  - argoproj.io
  resources:
  - workflows
  verbs:
  - create
  - get
  - list
  - watch
- apiGroups:
  - ''
  resources:
  - pods
  - configmaps
  - secrets
  verbs:
  - create
  - get
  - list
  - watch
